---
abstract: 'Plack middleware to minify HTML on-the-fly'
author:
  - 'Gea-Suan Lin <gslin@gslin.org>'
build_requires:
  HTTP::Request::Common: 0
  Module::Build: 0.3601
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-HTMLMinify
requires:
  HTML::Packer: 0
  Plack::Middleware: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  parent: 0
resources:
  homepage: https://github.com/gslin/plack-middleware-htmlminify-perl
  repository: https://github.com/gslin/plack-middleware-htmlminify-perl.git
version: 0.6.0
