---
abstract: 'Plack middleware to minify HTML on-the-fly'
author:
  - 'Gea-Suan Lin <gslin@gslin.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-HTMLMinify
requires:
  HTML::Packer: 0
  Plack: 0
version: 0.2
